name: lyrics_parser
description: >-
  .lrc file parser and lyrics tracker.
version: 1.0.0-nullsafety.0
homepage: https://github.com/fusee-code-lab/lyrics_parser

environment:
  sdk: ">=3.0.0"

dependencies:
  characters: ^1.4.0
  path: ^1.9.1

dev_dependencies:
  test: ^1.25.14
  lints: ^5.1.1
